name: Regenerate lockfile (Node 22)

on:
  workflow_dispatch:

jobs:
  regen-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'npm'
      - run: node -v && npm -v
      - run: rm -rf node_modules package-lock.json
      - run: npm install
      - name: Create PR with new lockfile
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: regenerate package-lock.json on Node 22.12"
          title: "Regenerate lockfile on Node 22.12"
          branch: chore/lockfile-node22
          add-paths: |
            package-lock.json
